### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by JonasKruckenberg** [probablykasper/time-machine-inspector#1]
I wanted to provide some feedback on your app, hope it helps 😄 

1. Open the settings **after** user confirmation, i.e. make this a prompt not a message:
   https://github.com/probablykasper/time-machine-inspector/blob/0c2943da3925fae64f2f685173b86f8af37454d0/src-tauri/src/cmd.rs#L38-L49
2. I don't have time machine backup enabled right now (yes I can hear you say this isn't the right app for me then 😉) but I feel like you could improve this error feedback!
    <img width="1010" alt="Screen Shot 2022-01-28 at 09 34 52" src="https://user-images.githubusercontent.com/25329995/151514038-7d7b0512-e847-4567-941a-fb4f936b86f0.png">

**Comment by probablykasper** [comment]
> Open the settings after user confirmation, i.e. make this a prompt not a message

Got any suggestion for how to handle that, and what text to show? Right now it kinda shows the instructions in the dialog, so it won't be as useful if it opens it after the dialog is closed.

> I don't have time machine backup enabled right now (yes I can hear you say this isn't the right app for me then 😉) but I feel like you could improve this error feedback!

Good idea, I'll look into that one!

**Comment by JonasKruckenberg** [comment]
> Got any suggestion for how to handle that, and what text to show? Right now it kinda shows the instructions in the dialog, so it won't be as useful if it opens it after the dialog is closed.

Hmm let's see, my main issue was that starting the app opened like 3 prompts on top of each other without warning. It'd be good UX practice to let the user cause that action intentionally.

I also think (though I might be wrong) that one of those prompts was macOS itself prompting me for full disk access, so this whole process would be redundant maybe?

Regardless I think your instructions are fine, if you tell users that full disk access is needed + you already open them the correct menu, I think they can click then checkbox even if the instructions are gone 😁

**Comment by probablykasper** [comment]
> I also think (though I might be wrong) that one of those prompts was macOS itself prompting me for full disk access, so this whole process would be redundant maybe?

I'm not getting that dialog at all, so not too sure what to do about it. Ideally there would be a "Show  Privacy Preferences" button once Tauri supports it, then maybe the app should quit after that.

**Comment by probablykasper** [comment]
Not quite sure how to reword it, but in the future I'll add a `Show Privacy Preferences` button once Tauri supports that
